// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DAOGrpc.proto

package com.netflix.dynomitemanager.identity;

/**
 * <pre>
 * The request message containing the fields for AppsInstanceFields.
 * </pre>
 *
 * Protobuf type {@code com.netflix.dynomitemanager.identity.AppsInstanceFields}
 */
public  final class AppsInstanceFields extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.netflix.dynomitemanager.identity.AppsInstanceFields)
    AppsInstanceFieldsOrBuilder {
  // Use AppsInstanceFields.newBuilder() to construct.
  private AppsInstanceFields(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AppsInstanceFields() {
    cNID_ = "";
    cNAPPID_ = "";
    cNAZ_ = "";
    cNDC_ = "";
    cNINSTANCEID_ = "";
    cNHOSTNAME_ = "";
    cNEIP_ = "";
    cNTOKEN_ = "";
    cNLOCATION_ = "";
    cNUPDATETIME_ = "";
    volumes_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private AppsInstanceFields(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            cNID_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            cNAPPID_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            cNAZ_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            cNDC_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            cNINSTANCEID_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            cNHOSTNAME_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            cNEIP_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            cNTOKEN_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            cNLOCATION_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            cNUPDATETIME_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            volumes_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.netflix.dynomitemanager.identity.InstanceDataDAOGrpc.internal_static_com_netflix_dynomitemanager_identity_AppsInstanceFields_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.netflix.dynomitemanager.identity.InstanceDataDAOGrpc.internal_static_com_netflix_dynomitemanager_identity_AppsInstanceFields_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.netflix.dynomitemanager.identity.AppsInstanceFields.class, com.netflix.dynomitemanager.identity.AppsInstanceFields.Builder.class);
  }

  public static final int CN_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object cNID_;
  /**
   * <code>optional string CN_ID = 1;</code>
   */
  public java.lang.String getCNID() {
    java.lang.Object ref = cNID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cNID_ = s;
      return s;
    }
  }
  /**
   * <code>optional string CN_ID = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCNIDBytes() {
    java.lang.Object ref = cNID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cNID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CN_APPID_FIELD_NUMBER = 2;
  private volatile java.lang.Object cNAPPID_;
  /**
   * <code>optional string CN_APPID = 2;</code>
   */
  public java.lang.String getCNAPPID() {
    java.lang.Object ref = cNAPPID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cNAPPID_ = s;
      return s;
    }
  }
  /**
   * <code>optional string CN_APPID = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCNAPPIDBytes() {
    java.lang.Object ref = cNAPPID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cNAPPID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CN_AZ_FIELD_NUMBER = 3;
  private volatile java.lang.Object cNAZ_;
  /**
   * <code>optional string CN_AZ = 3;</code>
   */
  public java.lang.String getCNAZ() {
    java.lang.Object ref = cNAZ_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cNAZ_ = s;
      return s;
    }
  }
  /**
   * <code>optional string CN_AZ = 3;</code>
   */
  public com.google.protobuf.ByteString
      getCNAZBytes() {
    java.lang.Object ref = cNAZ_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cNAZ_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CN_DC_FIELD_NUMBER = 4;
  private volatile java.lang.Object cNDC_;
  /**
   * <code>optional string CN_DC = 4;</code>
   */
  public java.lang.String getCNDC() {
    java.lang.Object ref = cNDC_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cNDC_ = s;
      return s;
    }
  }
  /**
   * <code>optional string CN_DC = 4;</code>
   */
  public com.google.protobuf.ByteString
      getCNDCBytes() {
    java.lang.Object ref = cNDC_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cNDC_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CN_INSTANCEID_FIELD_NUMBER = 5;
  private volatile java.lang.Object cNINSTANCEID_;
  /**
   * <code>optional string CN_INSTANCEID = 5;</code>
   */
  public java.lang.String getCNINSTANCEID() {
    java.lang.Object ref = cNINSTANCEID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cNINSTANCEID_ = s;
      return s;
    }
  }
  /**
   * <code>optional string CN_INSTANCEID = 5;</code>
   */
  public com.google.protobuf.ByteString
      getCNINSTANCEIDBytes() {
    java.lang.Object ref = cNINSTANCEID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cNINSTANCEID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CN_HOSTNAME_FIELD_NUMBER = 6;
  private volatile java.lang.Object cNHOSTNAME_;
  /**
   * <code>optional string CN_HOSTNAME = 6;</code>
   */
  public java.lang.String getCNHOSTNAME() {
    java.lang.Object ref = cNHOSTNAME_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cNHOSTNAME_ = s;
      return s;
    }
  }
  /**
   * <code>optional string CN_HOSTNAME = 6;</code>
   */
  public com.google.protobuf.ByteString
      getCNHOSTNAMEBytes() {
    java.lang.Object ref = cNHOSTNAME_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cNHOSTNAME_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CN_EIP_FIELD_NUMBER = 7;
  private volatile java.lang.Object cNEIP_;
  /**
   * <code>optional string CN_EIP = 7;</code>
   */
  public java.lang.String getCNEIP() {
    java.lang.Object ref = cNEIP_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cNEIP_ = s;
      return s;
    }
  }
  /**
   * <code>optional string CN_EIP = 7;</code>
   */
  public com.google.protobuf.ByteString
      getCNEIPBytes() {
    java.lang.Object ref = cNEIP_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cNEIP_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CN_TOKEN_FIELD_NUMBER = 8;
  private volatile java.lang.Object cNTOKEN_;
  /**
   * <code>optional string CN_TOKEN = 8;</code>
   */
  public java.lang.String getCNTOKEN() {
    java.lang.Object ref = cNTOKEN_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cNTOKEN_ = s;
      return s;
    }
  }
  /**
   * <code>optional string CN_TOKEN = 8;</code>
   */
  public com.google.protobuf.ByteString
      getCNTOKENBytes() {
    java.lang.Object ref = cNTOKEN_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cNTOKEN_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CN_LOCATION_FIELD_NUMBER = 9;
  private volatile java.lang.Object cNLOCATION_;
  /**
   * <code>optional string CN_LOCATION = 9;</code>
   */
  public java.lang.String getCNLOCATION() {
    java.lang.Object ref = cNLOCATION_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cNLOCATION_ = s;
      return s;
    }
  }
  /**
   * <code>optional string CN_LOCATION = 9;</code>
   */
  public com.google.protobuf.ByteString
      getCNLOCATIONBytes() {
    java.lang.Object ref = cNLOCATION_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cNLOCATION_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CN_UPDATETIME_FIELD_NUMBER = 10;
  private volatile java.lang.Object cNUPDATETIME_;
  /**
   * <code>optional string CN_UPDATETIME = 10;</code>
   */
  public java.lang.String getCNUPDATETIME() {
    java.lang.Object ref = cNUPDATETIME_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cNUPDATETIME_ = s;
      return s;
    }
  }
  /**
   * <code>optional string CN_UPDATETIME = 10;</code>
   */
  public com.google.protobuf.ByteString
      getCNUPDATETIMEBytes() {
    java.lang.Object ref = cNUPDATETIME_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cNUPDATETIME_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VOLUMES_FIELD_NUMBER = 11;
  private volatile java.lang.Object volumes_;
  /**
   * <code>optional string volumes = 11;</code>
   */
  public java.lang.String getVolumes() {
    java.lang.Object ref = volumes_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      volumes_ = s;
      return s;
    }
  }
  /**
   * <code>optional string volumes = 11;</code>
   */
  public com.google.protobuf.ByteString
      getVolumesBytes() {
    java.lang.Object ref = volumes_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      volumes_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCNIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cNID_);
    }
    if (!getCNAPPIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cNAPPID_);
    }
    if (!getCNAZBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cNAZ_);
    }
    if (!getCNDCBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, cNDC_);
    }
    if (!getCNINSTANCEIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, cNINSTANCEID_);
    }
    if (!getCNHOSTNAMEBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, cNHOSTNAME_);
    }
    if (!getCNEIPBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, cNEIP_);
    }
    if (!getCNTOKENBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, cNTOKEN_);
    }
    if (!getCNLOCATIONBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, cNLOCATION_);
    }
    if (!getCNUPDATETIMEBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, cNUPDATETIME_);
    }
    if (!getVolumesBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, volumes_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCNIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cNID_);
    }
    if (!getCNAPPIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cNAPPID_);
    }
    if (!getCNAZBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, cNAZ_);
    }
    if (!getCNDCBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, cNDC_);
    }
    if (!getCNINSTANCEIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, cNINSTANCEID_);
    }
    if (!getCNHOSTNAMEBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, cNHOSTNAME_);
    }
    if (!getCNEIPBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, cNEIP_);
    }
    if (!getCNTOKENBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, cNTOKEN_);
    }
    if (!getCNLOCATIONBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, cNLOCATION_);
    }
    if (!getCNUPDATETIMEBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, cNUPDATETIME_);
    }
    if (!getVolumesBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, volumes_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.netflix.dynomitemanager.identity.AppsInstanceFields)) {
      return super.equals(obj);
    }
    com.netflix.dynomitemanager.identity.AppsInstanceFields other = (com.netflix.dynomitemanager.identity.AppsInstanceFields) obj;

    boolean result = true;
    result = result && getCNID()
        .equals(other.getCNID());
    result = result && getCNAPPID()
        .equals(other.getCNAPPID());
    result = result && getCNAZ()
        .equals(other.getCNAZ());
    result = result && getCNDC()
        .equals(other.getCNDC());
    result = result && getCNINSTANCEID()
        .equals(other.getCNINSTANCEID());
    result = result && getCNHOSTNAME()
        .equals(other.getCNHOSTNAME());
    result = result && getCNEIP()
        .equals(other.getCNEIP());
    result = result && getCNTOKEN()
        .equals(other.getCNTOKEN());
    result = result && getCNLOCATION()
        .equals(other.getCNLOCATION());
    result = result && getCNUPDATETIME()
        .equals(other.getCNUPDATETIME());
    result = result && getVolumes()
        .equals(other.getVolumes());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + CN_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCNID().hashCode();
    hash = (37 * hash) + CN_APPID_FIELD_NUMBER;
    hash = (53 * hash) + getCNAPPID().hashCode();
    hash = (37 * hash) + CN_AZ_FIELD_NUMBER;
    hash = (53 * hash) + getCNAZ().hashCode();
    hash = (37 * hash) + CN_DC_FIELD_NUMBER;
    hash = (53 * hash) + getCNDC().hashCode();
    hash = (37 * hash) + CN_INSTANCEID_FIELD_NUMBER;
    hash = (53 * hash) + getCNINSTANCEID().hashCode();
    hash = (37 * hash) + CN_HOSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getCNHOSTNAME().hashCode();
    hash = (37 * hash) + CN_EIP_FIELD_NUMBER;
    hash = (53 * hash) + getCNEIP().hashCode();
    hash = (37 * hash) + CN_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getCNTOKEN().hashCode();
    hash = (37 * hash) + CN_LOCATION_FIELD_NUMBER;
    hash = (53 * hash) + getCNLOCATION().hashCode();
    hash = (37 * hash) + CN_UPDATETIME_FIELD_NUMBER;
    hash = (53 * hash) + getCNUPDATETIME().hashCode();
    hash = (37 * hash) + VOLUMES_FIELD_NUMBER;
    hash = (53 * hash) + getVolumes().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.netflix.dynomitemanager.identity.AppsInstanceFields parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.netflix.dynomitemanager.identity.AppsInstanceFields parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.netflix.dynomitemanager.identity.AppsInstanceFields parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.netflix.dynomitemanager.identity.AppsInstanceFields parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.netflix.dynomitemanager.identity.AppsInstanceFields parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.netflix.dynomitemanager.identity.AppsInstanceFields parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.netflix.dynomitemanager.identity.AppsInstanceFields parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.netflix.dynomitemanager.identity.AppsInstanceFields parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.netflix.dynomitemanager.identity.AppsInstanceFields parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.netflix.dynomitemanager.identity.AppsInstanceFields parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.netflix.dynomitemanager.identity.AppsInstanceFields prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The request message containing the fields for AppsInstanceFields.
   * </pre>
   *
   * Protobuf type {@code com.netflix.dynomitemanager.identity.AppsInstanceFields}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.netflix.dynomitemanager.identity.AppsInstanceFields)
      com.netflix.dynomitemanager.identity.AppsInstanceFieldsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netflix.dynomitemanager.identity.InstanceDataDAOGrpc.internal_static_com_netflix_dynomitemanager_identity_AppsInstanceFields_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netflix.dynomitemanager.identity.InstanceDataDAOGrpc.internal_static_com_netflix_dynomitemanager_identity_AppsInstanceFields_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netflix.dynomitemanager.identity.AppsInstanceFields.class, com.netflix.dynomitemanager.identity.AppsInstanceFields.Builder.class);
    }

    // Construct using com.netflix.dynomitemanager.identity.AppsInstanceFields.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      cNID_ = "";

      cNAPPID_ = "";

      cNAZ_ = "";

      cNDC_ = "";

      cNINSTANCEID_ = "";

      cNHOSTNAME_ = "";

      cNEIP_ = "";

      cNTOKEN_ = "";

      cNLOCATION_ = "";

      cNUPDATETIME_ = "";

      volumes_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.netflix.dynomitemanager.identity.InstanceDataDAOGrpc.internal_static_com_netflix_dynomitemanager_identity_AppsInstanceFields_descriptor;
    }

    public com.netflix.dynomitemanager.identity.AppsInstanceFields getDefaultInstanceForType() {
      return com.netflix.dynomitemanager.identity.AppsInstanceFields.getDefaultInstance();
    }

    public com.netflix.dynomitemanager.identity.AppsInstanceFields build() {
      com.netflix.dynomitemanager.identity.AppsInstanceFields result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.netflix.dynomitemanager.identity.AppsInstanceFields buildPartial() {
      com.netflix.dynomitemanager.identity.AppsInstanceFields result = new com.netflix.dynomitemanager.identity.AppsInstanceFields(this);
      result.cNID_ = cNID_;
      result.cNAPPID_ = cNAPPID_;
      result.cNAZ_ = cNAZ_;
      result.cNDC_ = cNDC_;
      result.cNINSTANCEID_ = cNINSTANCEID_;
      result.cNHOSTNAME_ = cNHOSTNAME_;
      result.cNEIP_ = cNEIP_;
      result.cNTOKEN_ = cNTOKEN_;
      result.cNLOCATION_ = cNLOCATION_;
      result.cNUPDATETIME_ = cNUPDATETIME_;
      result.volumes_ = volumes_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.netflix.dynomitemanager.identity.AppsInstanceFields) {
        return mergeFrom((com.netflix.dynomitemanager.identity.AppsInstanceFields)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.netflix.dynomitemanager.identity.AppsInstanceFields other) {
      if (other == com.netflix.dynomitemanager.identity.AppsInstanceFields.getDefaultInstance()) return this;
      if (!other.getCNID().isEmpty()) {
        cNID_ = other.cNID_;
        onChanged();
      }
      if (!other.getCNAPPID().isEmpty()) {
        cNAPPID_ = other.cNAPPID_;
        onChanged();
      }
      if (!other.getCNAZ().isEmpty()) {
        cNAZ_ = other.cNAZ_;
        onChanged();
      }
      if (!other.getCNDC().isEmpty()) {
        cNDC_ = other.cNDC_;
        onChanged();
      }
      if (!other.getCNINSTANCEID().isEmpty()) {
        cNINSTANCEID_ = other.cNINSTANCEID_;
        onChanged();
      }
      if (!other.getCNHOSTNAME().isEmpty()) {
        cNHOSTNAME_ = other.cNHOSTNAME_;
        onChanged();
      }
      if (!other.getCNEIP().isEmpty()) {
        cNEIP_ = other.cNEIP_;
        onChanged();
      }
      if (!other.getCNTOKEN().isEmpty()) {
        cNTOKEN_ = other.cNTOKEN_;
        onChanged();
      }
      if (!other.getCNLOCATION().isEmpty()) {
        cNLOCATION_ = other.cNLOCATION_;
        onChanged();
      }
      if (!other.getCNUPDATETIME().isEmpty()) {
        cNUPDATETIME_ = other.cNUPDATETIME_;
        onChanged();
      }
      if (!other.getVolumes().isEmpty()) {
        volumes_ = other.volumes_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.netflix.dynomitemanager.identity.AppsInstanceFields parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.netflix.dynomitemanager.identity.AppsInstanceFields) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object cNID_ = "";
    /**
     * <code>optional string CN_ID = 1;</code>
     */
    public java.lang.String getCNID() {
      java.lang.Object ref = cNID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cNID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string CN_ID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCNIDBytes() {
      java.lang.Object ref = cNID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cNID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string CN_ID = 1;</code>
     */
    public Builder setCNID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cNID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string CN_ID = 1;</code>
     */
    public Builder clearCNID() {
      
      cNID_ = getDefaultInstance().getCNID();
      onChanged();
      return this;
    }
    /**
     * <code>optional string CN_ID = 1;</code>
     */
    public Builder setCNIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cNID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cNAPPID_ = "";
    /**
     * <code>optional string CN_APPID = 2;</code>
     */
    public java.lang.String getCNAPPID() {
      java.lang.Object ref = cNAPPID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cNAPPID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string CN_APPID = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCNAPPIDBytes() {
      java.lang.Object ref = cNAPPID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cNAPPID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string CN_APPID = 2;</code>
     */
    public Builder setCNAPPID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cNAPPID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string CN_APPID = 2;</code>
     */
    public Builder clearCNAPPID() {
      
      cNAPPID_ = getDefaultInstance().getCNAPPID();
      onChanged();
      return this;
    }
    /**
     * <code>optional string CN_APPID = 2;</code>
     */
    public Builder setCNAPPIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cNAPPID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cNAZ_ = "";
    /**
     * <code>optional string CN_AZ = 3;</code>
     */
    public java.lang.String getCNAZ() {
      java.lang.Object ref = cNAZ_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cNAZ_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string CN_AZ = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCNAZBytes() {
      java.lang.Object ref = cNAZ_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cNAZ_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string CN_AZ = 3;</code>
     */
    public Builder setCNAZ(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cNAZ_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string CN_AZ = 3;</code>
     */
    public Builder clearCNAZ() {
      
      cNAZ_ = getDefaultInstance().getCNAZ();
      onChanged();
      return this;
    }
    /**
     * <code>optional string CN_AZ = 3;</code>
     */
    public Builder setCNAZBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cNAZ_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cNDC_ = "";
    /**
     * <code>optional string CN_DC = 4;</code>
     */
    public java.lang.String getCNDC() {
      java.lang.Object ref = cNDC_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cNDC_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string CN_DC = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCNDCBytes() {
      java.lang.Object ref = cNDC_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cNDC_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string CN_DC = 4;</code>
     */
    public Builder setCNDC(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cNDC_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string CN_DC = 4;</code>
     */
    public Builder clearCNDC() {
      
      cNDC_ = getDefaultInstance().getCNDC();
      onChanged();
      return this;
    }
    /**
     * <code>optional string CN_DC = 4;</code>
     */
    public Builder setCNDCBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cNDC_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cNINSTANCEID_ = "";
    /**
     * <code>optional string CN_INSTANCEID = 5;</code>
     */
    public java.lang.String getCNINSTANCEID() {
      java.lang.Object ref = cNINSTANCEID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cNINSTANCEID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string CN_INSTANCEID = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCNINSTANCEIDBytes() {
      java.lang.Object ref = cNINSTANCEID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cNINSTANCEID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string CN_INSTANCEID = 5;</code>
     */
    public Builder setCNINSTANCEID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cNINSTANCEID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string CN_INSTANCEID = 5;</code>
     */
    public Builder clearCNINSTANCEID() {
      
      cNINSTANCEID_ = getDefaultInstance().getCNINSTANCEID();
      onChanged();
      return this;
    }
    /**
     * <code>optional string CN_INSTANCEID = 5;</code>
     */
    public Builder setCNINSTANCEIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cNINSTANCEID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cNHOSTNAME_ = "";
    /**
     * <code>optional string CN_HOSTNAME = 6;</code>
     */
    public java.lang.String getCNHOSTNAME() {
      java.lang.Object ref = cNHOSTNAME_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cNHOSTNAME_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string CN_HOSTNAME = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCNHOSTNAMEBytes() {
      java.lang.Object ref = cNHOSTNAME_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cNHOSTNAME_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string CN_HOSTNAME = 6;</code>
     */
    public Builder setCNHOSTNAME(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cNHOSTNAME_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string CN_HOSTNAME = 6;</code>
     */
    public Builder clearCNHOSTNAME() {
      
      cNHOSTNAME_ = getDefaultInstance().getCNHOSTNAME();
      onChanged();
      return this;
    }
    /**
     * <code>optional string CN_HOSTNAME = 6;</code>
     */
    public Builder setCNHOSTNAMEBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cNHOSTNAME_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cNEIP_ = "";
    /**
     * <code>optional string CN_EIP = 7;</code>
     */
    public java.lang.String getCNEIP() {
      java.lang.Object ref = cNEIP_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cNEIP_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string CN_EIP = 7;</code>
     */
    public com.google.protobuf.ByteString
        getCNEIPBytes() {
      java.lang.Object ref = cNEIP_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cNEIP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string CN_EIP = 7;</code>
     */
    public Builder setCNEIP(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cNEIP_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string CN_EIP = 7;</code>
     */
    public Builder clearCNEIP() {
      
      cNEIP_ = getDefaultInstance().getCNEIP();
      onChanged();
      return this;
    }
    /**
     * <code>optional string CN_EIP = 7;</code>
     */
    public Builder setCNEIPBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cNEIP_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cNTOKEN_ = "";
    /**
     * <code>optional string CN_TOKEN = 8;</code>
     */
    public java.lang.String getCNTOKEN() {
      java.lang.Object ref = cNTOKEN_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cNTOKEN_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string CN_TOKEN = 8;</code>
     */
    public com.google.protobuf.ByteString
        getCNTOKENBytes() {
      java.lang.Object ref = cNTOKEN_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cNTOKEN_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string CN_TOKEN = 8;</code>
     */
    public Builder setCNTOKEN(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cNTOKEN_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string CN_TOKEN = 8;</code>
     */
    public Builder clearCNTOKEN() {
      
      cNTOKEN_ = getDefaultInstance().getCNTOKEN();
      onChanged();
      return this;
    }
    /**
     * <code>optional string CN_TOKEN = 8;</code>
     */
    public Builder setCNTOKENBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cNTOKEN_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cNLOCATION_ = "";
    /**
     * <code>optional string CN_LOCATION = 9;</code>
     */
    public java.lang.String getCNLOCATION() {
      java.lang.Object ref = cNLOCATION_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cNLOCATION_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string CN_LOCATION = 9;</code>
     */
    public com.google.protobuf.ByteString
        getCNLOCATIONBytes() {
      java.lang.Object ref = cNLOCATION_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cNLOCATION_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string CN_LOCATION = 9;</code>
     */
    public Builder setCNLOCATION(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cNLOCATION_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string CN_LOCATION = 9;</code>
     */
    public Builder clearCNLOCATION() {
      
      cNLOCATION_ = getDefaultInstance().getCNLOCATION();
      onChanged();
      return this;
    }
    /**
     * <code>optional string CN_LOCATION = 9;</code>
     */
    public Builder setCNLOCATIONBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cNLOCATION_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cNUPDATETIME_ = "";
    /**
     * <code>optional string CN_UPDATETIME = 10;</code>
     */
    public java.lang.String getCNUPDATETIME() {
      java.lang.Object ref = cNUPDATETIME_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cNUPDATETIME_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string CN_UPDATETIME = 10;</code>
     */
    public com.google.protobuf.ByteString
        getCNUPDATETIMEBytes() {
      java.lang.Object ref = cNUPDATETIME_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cNUPDATETIME_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string CN_UPDATETIME = 10;</code>
     */
    public Builder setCNUPDATETIME(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cNUPDATETIME_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string CN_UPDATETIME = 10;</code>
     */
    public Builder clearCNUPDATETIME() {
      
      cNUPDATETIME_ = getDefaultInstance().getCNUPDATETIME();
      onChanged();
      return this;
    }
    /**
     * <code>optional string CN_UPDATETIME = 10;</code>
     */
    public Builder setCNUPDATETIMEBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cNUPDATETIME_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object volumes_ = "";
    /**
     * <code>optional string volumes = 11;</code>
     */
    public java.lang.String getVolumes() {
      java.lang.Object ref = volumes_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        volumes_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string volumes = 11;</code>
     */
    public com.google.protobuf.ByteString
        getVolumesBytes() {
      java.lang.Object ref = volumes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        volumes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string volumes = 11;</code>
     */
    public Builder setVolumes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      volumes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string volumes = 11;</code>
     */
    public Builder clearVolumes() {
      
      volumes_ = getDefaultInstance().getVolumes();
      onChanged();
      return this;
    }
    /**
     * <code>optional string volumes = 11;</code>
     */
    public Builder setVolumesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      volumes_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.netflix.dynomitemanager.identity.AppsInstanceFields)
  }

  // @@protoc_insertion_point(class_scope:com.netflix.dynomitemanager.identity.AppsInstanceFields)
  private static final com.netflix.dynomitemanager.identity.AppsInstanceFields DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.netflix.dynomitemanager.identity.AppsInstanceFields();
  }

  public static com.netflix.dynomitemanager.identity.AppsInstanceFields getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AppsInstanceFields>
      PARSER = new com.google.protobuf.AbstractParser<AppsInstanceFields>() {
    public AppsInstanceFields parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new AppsInstanceFields(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AppsInstanceFields> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AppsInstanceFields> getParserForType() {
    return PARSER;
  }

  public com.netflix.dynomitemanager.identity.AppsInstanceFields getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

