// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DAOGrpc.proto

package com.netflix.dynomitemanager.identity;

public interface AppsInstanceFieldsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.netflix.dynomitemanager.identity.AppsInstanceFields)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string CN_ID = 1;</code>
   */
  java.lang.String getCNID();
  /**
   * <code>optional string CN_ID = 1;</code>
   */
  com.google.protobuf.ByteString
      getCNIDBytes();

  /**
   * <code>optional string CN_APPID = 2;</code>
   */
  java.lang.String getCNAPPID();
  /**
   * <code>optional string CN_APPID = 2;</code>
   */
  com.google.protobuf.ByteString
      getCNAPPIDBytes();

  /**
   * <code>optional string CN_AZ = 3;</code>
   */
  java.lang.String getCNAZ();
  /**
   * <code>optional string CN_AZ = 3;</code>
   */
  com.google.protobuf.ByteString
      getCNAZBytes();

  /**
   * <code>optional string CN_DC = 4;</code>
   */
  java.lang.String getCNDC();
  /**
   * <code>optional string CN_DC = 4;</code>
   */
  com.google.protobuf.ByteString
      getCNDCBytes();

  /**
   * <code>optional string CN_INSTANCEID = 5;</code>
   */
  java.lang.String getCNINSTANCEID();
  /**
   * <code>optional string CN_INSTANCEID = 5;</code>
   */
  com.google.protobuf.ByteString
      getCNINSTANCEIDBytes();

  /**
   * <code>optional string CN_HOSTNAME = 6;</code>
   */
  java.lang.String getCNHOSTNAME();
  /**
   * <code>optional string CN_HOSTNAME = 6;</code>
   */
  com.google.protobuf.ByteString
      getCNHOSTNAMEBytes();

  /**
   * <code>optional string CN_EIP = 7;</code>
   */
  java.lang.String getCNEIP();
  /**
   * <code>optional string CN_EIP = 7;</code>
   */
  com.google.protobuf.ByteString
      getCNEIPBytes();

  /**
   * <code>optional string CN_TOKEN = 8;</code>
   */
  java.lang.String getCNTOKEN();
  /**
   * <code>optional string CN_TOKEN = 8;</code>
   */
  com.google.protobuf.ByteString
      getCNTOKENBytes();

  /**
   * <code>optional string CN_LOCATION = 9;</code>
   */
  java.lang.String getCNLOCATION();
  /**
   * <code>optional string CN_LOCATION = 9;</code>
   */
  com.google.protobuf.ByteString
      getCNLOCATIONBytes();

  /**
   * <code>optional string CN_UPDATETIME = 10;</code>
   */
  java.lang.String getCNUPDATETIME();
  /**
   * <code>optional string CN_UPDATETIME = 10;</code>
   */
  com.google.protobuf.ByteString
      getCNUPDATETIMEBytes();

  /**
   * <code>optional string volumes = 11;</code>
   */
  java.lang.String getVolumes();
  /**
   * <code>optional string volumes = 11;</code>
   */
  com.google.protobuf.ByteString
      getVolumesBytes();
}
