// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DAOGrpc.proto

package com.netflix.dynomitemanager.identity;

public interface CRUDResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.netflix.dynomitemanager.identity.CRUDResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string response = 1;</code>
   */
  java.lang.String getResponse();
  /**
   * <code>optional string response = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
