// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DAOGrpc.proto

package com.netflix.dynomitemanager.identity;

public final class InstanceDataDAOGrpc {
  private InstanceDataDAOGrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_netflix_dynomitemanager_identity_AppsInstanceFields_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_netflix_dynomitemanager_identity_AppsInstanceFields_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_netflix_dynomitemanager_identity_CRUDResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_netflix_dynomitemanager_identity_CRUDResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rDAOGrpc.proto\022$com.netflix.dynomiteman" +
      "ager.identity\"\336\001\n\022AppsInstanceFields\022\r\n\005" +
      "CN_ID\030\001 \001(\t\022\020\n\010CN_APPID\030\002 \001(\t\022\r\n\005CN_AZ\030\003" +
      " \001(\t\022\r\n\005CN_DC\030\004 \001(\t\022\025\n\rCN_INSTANCEID\030\005 \001" +
      "(\t\022\023\n\013CN_HOSTNAME\030\006 \001(\t\022\016\n\006CN_EIP\030\007 \001(\t\022" +
      "\020\n\010CN_TOKEN\030\010 \001(\t\022\023\n\013CN_LOCATION\030\t \001(\t\022\025" +
      "\n\rCN_UPDATETIME\030\n \001(\t\022\017\n\007volumes\030\013 \001(\t\" " +
      "\n\014CRUDResponse\022\020\n\010response\030\001 \001(\t2\221\001\n\007DAO" +
      "Grpc\022\205\001\n\023CreateInstanceEntry\0228.com.netfl" +
      "ix.dynomitemanager.identity.AppsInstance",
      "Fields\0322.com.netflix.dynomitemanager.ide" +
      "ntity.CRUDResponse\"\000BG\n$com.netflix.dyno" +
      "mitemanager.identityB\023InstanceDataDAOGrp" +
      "cP\001\242\002\007DAOGrpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_netflix_dynomitemanager_identity_AppsInstanceFields_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_netflix_dynomitemanager_identity_AppsInstanceFields_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_netflix_dynomitemanager_identity_AppsInstanceFields_descriptor,
        new java.lang.String[] { "CNID", "CNAPPID", "CNAZ", "CNDC", "CNINSTANCEID", "CNHOSTNAME", "CNEIP", "CNTOKEN", "CNLOCATION", "CNUPDATETIME", "Volumes", });
    internal_static_com_netflix_dynomitemanager_identity_CRUDResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_netflix_dynomitemanager_identity_CRUDResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_netflix_dynomitemanager_identity_CRUDResponse_descriptor,
        new java.lang.String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
